### ISSUE TITLE
custom camera view

### ISSUE THREAD

**Issue by kelvinabrokwa** [wm-robo-ops/dashboard#10]

**Comment by Djruhnke** [comment]
Implemented in own tab but need to move into the all cameras tab.
https://github.com/wm-robo-ops/dashboard/commit/71e624e4a8393a2b02bd28075406af11931757a6

**Comment by kelvinabrokwa** [comment]
On the all cameras page you can now click on a camera to enlarge it and then click again (or press escape) to ensmall it
