### ISSUE TITLE
remove zoom/pan controls

### ISSUE THREAD

**Issue by kelvinabrokwa** [wm-robo-ops/dashboard#26]
fugly rn

**Comment by ajwells** [comment]
by fix you can just remove as I don't believe they will be implemented

**Comment by kelvinabrokwa** [comment]
@ajwells well that makes my job easier...

**Comment by ajwells** [comment]
@kelvinabrokwa just looking out for you fam

**Comment by kelvinabrokwa** [comment]
@ajwells :wink:
