### ISSUE TITLE
drag and drop photo interface for flyer interface

### ISSUE THREAD

**Issue by kelvinabrokwa** [wm-robo-ops/dashboard#47]

**Comment by ajwells** [comment]
idea: if they are on his computer can he just email them to one of us and we can just use sftp to put them on the server?

**Comment by kelvinabrokwa** [comment]
Also that. Should ask what they want?

**Comment by ajwells** [comment]
Yeah I can send an email tomorrow. I would assume they wouldn't care.

**Comment by kelvinabrokwa** [comment]
nah b
